name: Integration Test

on:
  schedule:
    - cron: '0 1 * * 1' # Every Monday at 9 AM (UTC+8)
  workflow_dispatch:
  workflow_call:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: package.json
      - run: npm install
      - run: npm run build
      - name: Install dependencies for integration test
        run: npm install
        working-directory: tests/integration
      - run: npm run test:integration
