name: Unit Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js based on `package.json`
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - run: npm install
      - run: npm run lint
      - run: |
          npm run test:unit -- \
            --coverage.reporter lcov \
            --reporter=junit --outputFile=test-report.junit.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

